# Generated by Django 3.1.5 on 2021-01-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birthday', models.DateField()),
                ('photo', models.ImageField(upload_to='artists')),
                ('description', models.TextField()),
                ('draft', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('draft', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Clip',
                'verbose_name_plural': 'Clips',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('draft', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Musical Genre',
                'verbose_name_plural': 'Musical Genres',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cover', models.ImageField(upload_to='covers')),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('lyrics', models.CharField(max_length=100)),
                ('draft', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.ManyToManyField(related_name='artist', to='lemni.Artist')),
                ('feature', models.ManyToManyField(blank=True, related_name='feature', to='lemni.Artist')),
                ('genre', models.ManyToManyField(to='lemni.Genre')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='clips',
            field=models.ManyToManyField(to='lemni.Clip'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='lemni.Genre'),
        ),
    ]
