# Generated by Django 3.1.5 on 2021-02-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
    ]
