# Generated by Django 3.1.5 on 2021-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='clips',
            field=models.ManyToManyField(blank=True, to='lemni.Clip'),
        ),
    ]
