# Generated by Django 3.1.5 on 2021-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemni', '0002_auto_20210224_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='lemni.Artist'),
        ),
    ]
