# Generated by Django 3.1.5 on 2021-01-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemni', '0002_auto_20210111_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
